name: SaltProc using Conda

on: [push, pull_request]

jobs:
  build-saltproc:
    runs-on: ubuntu-latest
    steps: 
      - uses: actions/checkout@v2
      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Add conda to system path
        run: |
          # $CONDA is an environment variable pointing to the root of the miniconda directory
          echo $CONDA/bin >> $GITHUB_PATH
      
      - name: Install system dependencies
        shell: bash
        run: |
          sudo apt -y update
          sudo apt install -y libhdf5-serial-dev \
                              gfortran \
                              gcc \
                              build-essential \
                              cmake \
                              libblas-dev \
                              liblapack-dev
                          
      - name: Install packages
        run: conda install -c conda-forge pyne numpy networkx pydotplus pytest
  
      - name: "Build SaltProc"
        run: python setup.py build
      
      - name: "Install SaltProc"
        run: python setup.py install --user
        
      - name: "Run test suite"
        run: pytest --ignore saltproc/tests/integration_tests saltproc
